name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android-emulator:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài đặt Android SDK
      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk wget unzip
          
          # Tải về và giải nén Android SDK command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip

          # Di chuyển Android SDK vào thư mục thích hợp
          sudo mkdir -p /usr/local/android-sdk
          sudo mv cmdline-tools /usr/local/android-sdk/
          
          # Cập nhật biến môi trường để có thể sử dụng sdkmanager và các công cụ khác
          echo "export ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\$PATH:/usr/local/android-sdk/cmdline-tools/bin:/usr/local/android-sdk/platform-tools:/usr/local/android-sdk/emulator:/usr/local/android-sdk/cmdline-tools/tools/bin" >> $GITHUB_ENV
          
          # Kiểm tra sdkmanager
          sdkmanager --version  # Kiểm tra sdkmanager để đảm bảo công cụ đã được cài đặt

          # Cài đặt SDK và hệ thống Android cần thiết
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"

      # 3. Cài đặt Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # 4. Cài đặt Appium Doctor để kiểm tra môi trường
      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor

      # 5. Tạo và khởi động Android Emulator
      - name: Start Android Emulator
        run: |
          # Tạo Android Virtual Device (AVD) cho emulator
          echo "no" | avdmanager create avd --name test_emulator --package "system-images;android-30;google_apis;x86_64"
          
          # Khởi động emulator trong nền (no-window để không có giao diện người dùng)
          nohup emulator -avd test_emulator -no-window -gpu off -qemu -m 2048 -enable-kvm & 
          sleep 120  # Đợi emulator khởi động

      # 6. Chạy các bài kiểm tra Appium
      - name: Run Appium tests
        run: |
          mvn clean test -Dappium.server=http://localhost:4723/wd/hub

      # 7. Dọn dẹp sau khi test xong
      - name: Stop Emulator
        run: |
          adb -s emulator-5554 emu kill
