name: Set up Java 21 and Build

on:
  push:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      # Bước này checkout mã nguồn của repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước này cài đặt Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          java-package: jdk
          check-latest: false

      # Bước này cài đặt Maven và cấu hình xác thực cho Maven (nếu cần)
      - name: Set up Maven and configure credentials
        run: |
          mkdir -p ~/.m2
          echo "<settings>" > ~/.m2/settings.xml
          echo "  <servers>" >> ~/.m2/settings.xml
          echo "    <server>" >> ~/.m2/settings.xml
          echo "      <id>github</id>" >> ~/.m2/settings.xml
          echo "      <username>${{ github.actor }}</username>" >> ~/.m2/settings.xml
          echo "      <password>${{ secrets.GITHUB_TOKEN }}</password>" >> ~/.m2/settings.xml
          echo "    </server>" >> ~/.m2/settings.xml
          echo "  </servers>" >> ~/.m2/settings.xml
          echo "</settings>" >> ~/.m2/settings.xml

      # Bước này chạy build và test với Maven
      - name: Build and test with Maven
        run: mvn clean install

      # Bước này gọi API GitHub để lấy thông tin người dùng (sử dụng GITHUB_TOKEN)
      - name: Make an API call to GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
