name: Set up Java 21 and Build

on:
  push:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cài đặt Java 21 với phân phối Temurin
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Cài đặt Maven
      - name: Set up Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      # Cài đặt Node.js và Appium
      - name: Set up Node.js and install Appium
        run: |
          sudo apt install -y nodejs
          sudo apt install -y npm
          npm install -g appium

      # Cài đặt các phụ thuộc (nếu có) cho các bài kiểm tra Appium
      - name: Install Appium dependencies
        run: |
          npm install appium @wdio/cli @wdio/appium-service

      # Di chuyển vào thư mục chứa pom.xml và chạy build và test với Maven
      - name: Build and test with Maven
        run: |
          cd android/testng-examples  # Thay đổi thư mục làm việc đến nơi chứa pom.xml
          mvn clean install

      # Chạy các bài kiểm tra Appium (Nếu bạn có script riêng cho Appium)
      - name: Run Appium tests with BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          appium &
          # Nếu bạn có file test Appium cụ thể, ví dụ như 'appium-tests.js', thì chạy lệnh sau:
          # npx wdio run ./wdio.conf.js

      # Gọi API GitHub
      - name: Make an API call to GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
