name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android-emulator:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài đặt Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # 3. Cài đặt Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # 4. Cài đặt Appium Doctor để kiểm tra môi trường
      - name: Install Appium Doctor
        run: |
          npm install -g appium-doctor
          appium-doctor

      # 5. Cài đặt hình ảnh hệ thống cho AVD
      - name: Install System Image for AVD
        run: |
          yes | sdkmanager "system-images;android-30;google_apis;x86_64"

      # 6. Tạo và khởi động Android Emulator
      - name: Start Android Emulator
        run: |
          # Tạo Android Virtual Device (AVD) cho emulator
          echo "no" | avdmanager create avd --name test_emulator --package "system-images;android-30;google_apis;x86_64"

          # Khởi động emulator trong nền (no-window để không có giao diện người dùng)
          nohup emulator -avd test_emulator -no-window -gpu off -qemu -m 2048 -enable-kvm & 
          sleep 120  # Đợi emulator khởi động

      # 7. Chạy các bài kiểm tra Appium
      - name: Run Appium tests
        run: |
          cd android/testng-examples  # Thay đổi đường dẫn đến thư mục chứa pom.xml
          mvn clean test -Dappium.server=http://localhost:4723/wd/hub

      # 8. Dọn dẹp sau khi test xong
      - name: Stop Emulator
        run: |
          adb -s emulator-5554 emu kill