name: Run Tests on BrowserStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Cài đặt Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Cài đặt các phụ thuộc Maven (Java 21)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          maven-version: '3.8.1'

      # Cài đặt các phụ thuộc và chạy test
      - name: Run tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          mvn clean test -Dtestng.xml=src/test/resources/com/browserstack/sample-test.testng.xml
