name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android-emulator:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài đặt Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # 3. Cài đặt Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # 4. Kiểm tra phiên bản Appium
      - name: Check Appium Version
        run: |
          appium -v

      # 5. Cài đặt driver Android cho Appium
      - name: Install Appium Android Driver
        run: |
          npm install -g appium-uiautomator2-driver

      # 6. Cài đặt hình ảnh hệ thống cho AVD (sử dụng x86_64)
      - name: Install System Image for AVD
        run: |
          yes | sdkmanager "system-images;android-30;google_apis;x86_64"

      # 7. Cài đặt Emulator
      - name: Install Emulator
        run: |
          yes | sdkmanager "emulator"

      # 8. Thêm đường dẫn vào PATH và kiểm tra
      - name: Set PATH and Check Emulator
        run: |
          export PATH=$PATH:$ANDROID_HOME/emulator
          export PATH=$PATH:$ANDROID_HOME/tools
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          echo "Checking if emulator is in PATH"
          which emulator || echo "Emulator not found in PATH"

      # 9. Tạo Android Emulator với hình ảnh x86_64
      - name: Create Android Emulator
        run: |
          avdmanager create avd --name test_emulator --package "system-images;android-30;google_apis;x86_64" --force --device "pixel" --tag "google_apis"

      # 10. Khởi động Android Emulator với tham số -no-accel
      - name: Start Android Emulator
        run: |
          export PATH=$PATH:$ANDROID_HOME/emulator
          bash -c "emulator -avd test_emulator -no-window -gpu off -no-accel &"
          sleep 240  # Tăng thời gian chờ để emulator khởi động

      # 11. Khởi động ADB daemon
      - name: Start ADB Daemon
        run: |
          adb start-server

      # 12. Kiểm tra trạng thái của Emulator
      - name: Check Emulator Status
        run: |
          adb wait-for-device
          adb devices || (echo "Emulator is not running." && exit 1)

      # 13. Dừng Appium Server nếu đang chạy
      - name: Stop Appium Server if running
        run: |
          if pgrep -f appium; then
            echo "Stopping existing Appium server..."
            pkill -f appium
          fi

      # 14. Khởi động Appium Server trên cổng khác (ví dụ: 4726)
      - name: Start Appium Server
        run: |
          appium -p 4726 | tee appium.log &  # Khởi động Appium server trên cổng 4726 và ghi log
          sleep 30  # Đợi một chút để server khởi động

      # 15. Kiểm tra trạng thái của Appium server
      - name: Check Appium Server Status
        run: |
          sleep 5  # Đợi một chút trước khi kiểm tra
          if curl -s http://localhost:4726/wd/hub/status | grep -q '"status": 0'; then
            echo "Appium server is running."
          else
            echo "Appium server is not running. Check appium.log for details."
            cat appium.log  # In log để kiểm tra lỗi
            exit 1
          fi

      # 16. Chạy các bài kiểm tra Appium
      - name: Run Appium tests
        run: |
          cd android/testng-examples  # Đảm bảo bạn đang ở đúng thư mục
          mvn clean test -Dappium.server=http://localhost:4726/wd/hub  # Sử dụng cổng 4726

      # 17. Dọn dẹp sau khi test xong
      - name: Stop Emulator
        run: |
          adb -s emulator-5554 emu kill