name: Use GitHub Token

on:
  push:
    branches:
      - main

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make an API call to GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
