name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - main

jobs:
  android-emulator:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài đặt Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # 3. Cài đặt Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # 4. Cài đặt driver Android cho Appium
      - name: Install Appium Android Driver
        run: |
          appium driver install uiautomator2

      # 5. Cài đặt hình ảnh hệ thống cho AVD
      - name: Install System Image for AVD
        run: |
          yes | sdkmanager "system-images;android-30;google_apis;x86_64"

      # 6. Tạo và khởi động Android Emulator
      - name: Start Android Emulator
        run: |
          echo "no" | avdmanager create avd --name test_emulator --package "system-images;android-30;google_apis;x86_64"
          nohup emulator -avd test_emulator -no-window -gpu off -qemu -m 2048 -enable-kvm & 
          sleep 180  # Đợi emulator khởi động

      # 7. Dừng Appium Server nếu đang chạy
      - name: Stop Appium Server if running
        run: |
          if pgrep -f appium; then
            echo "Stopping existing Appium server..."
            pkill -f appium
          fi

      # 8. Khởi động Appium Server trên cổng khác (ví dụ: 4726)
      - name: Start Appium Server
        run: |
          appium -p 4726 > appium.log 2>&1 &  # Khởi động Appium server trên cổng 4726 và ghi log
          sleep 30  # Đợi một chút để server khởi động

      # 9. Kiểm tra trạng thái của Appium server
      - name: Check Appium Server Status
        run: |
          curl -s http://localhost:4726/wd/hub/status | grep -q '"status": 0' || (echo "Appium server is not running." && exit 1)

      # 10. Kiểm tra trạng thái của Emulator
      - name: Check Emulator Status
        run: |
          adb devices || (echo "Emulator is not running." && exit 1)

      # 11. Chạy các bài kiểm tra Appium
      - name: Run Appium tests
        run: |
          cd android/testng-examples  # Đảm bảo bạn đang ở đúng thư mục
          mvn clean test -Dappium.server=http://localhost:4726/wd/hub  # Sử dụng cổng 4726

      # 12. Dọn dẹp sau khi test xong
      - name: Stop Emulator
        run: |
          adb -s emulator-5554 emu kill