name: Set up Java 21 and Build

on:
  push:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cài đặt Java 21 với phân phối Temurin
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Phân phối Temurin cho OpenJDK
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Cài đặt Maven (sử dụng action riêng biệt)
      - name: Set up Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      # Chạy build và test với Maven
      - name: Build and test with Maven
        run: mvn clean install

      # Gọi API GitHub
      - name: Make an API call to GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
