name: Set up Java 21, Build and Call GitHub API

on:
  push:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      # Bước này để checkout mã nguồn của repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước này cài đặt Java 21 và Maven
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Bước này cài đặt Maven và build dự án
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          maven-version: '3.8.1'

      # Bước này chạy build Maven và test
      - name: Build and test with Maven
        run: mvn clean install

      # Bước này gọi API GitHub để lấy thông tin người dùng
      - name: Make an API call to GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
