name: Set up Java 21 and Build

on:
  push:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      # Bước này để checkout mã nguồn của repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước này thiết lập Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Bước này sẽ xây dựng và chạy test với Maven
      - name: Build and test with Maven
        run: mvn clean install
